### ISSUE TITLE
Parser should be more robust in injecting dates

### ISSUE THREAD

**Issue by mouradvt04** [rayyanqcri/ref_parsers#6]
We've got few tickets because of an error parsing the date.
In the particular case of RIS, "PY" is the Publication year which can also have the month and the day (e.g., YYYY/MM/DD or YYYYMMDD).
We should not send erroneous dates to PostgreSQL, we should try our best effort to recognize the date and if all fail then put a null value.

**Comment by hammady** [comment]
The correct repo and line of code for this issue are [here](https://github.com/rayyanqcri/rayyan-formats-plugins/blob/master/lib/rayyan-formats-plugins/plugins/refman.rb#L79). Please move. Another thing is that we do our best effort in sanitizing date values before sending to postgres. Actually we make sure it is a valid Ruby date before sending to postgres. Unfortunately, not all ruby dates are valid postgres dates. Please check the sanization [here](https://github.com/qcri/rayyan/blob/master/lib/date_utils.rb).
